services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service


  bookingdb:
    container_name: bookingdb
    platform: linux/amd64
    image: postgres:15
    ports:
      - 5440:5432
    volumes:
      - ./postgres-init/booking:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bookingdb
    extends:
      file: common-config.yml
      service: base-postgres-network-config


  notificationdb:
    container_name: notificationdb
    platform: linux/amd64
    image: postgres:15
    ports:
      - 5441:5432
    volumes:
      - ./postgres-init/notification:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notificationdb
    extends:
      file: common-config.yml
      service: base-postgres-network-config

  configserver:
    image: "keskink/configserver:v1"
    container_name: configserverms
    platform: linux/amd64
    ports:
      - "8888:8888"
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config


  eurekaserver:
    image: "keskink/eurekaserver:v1"
    container_name: eurekaserverms
    platform: linux/amd64
    ports:
      - "8761:8761"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      SERVER_PORT: 8761

  bookings:
    image: "keskink/bookingservice:v1"
    container_name: bookingms
    platform: linux/amd64
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "bookingservice"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://bookingdb:5432/bookingdb"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      rabbit:
        condition: service_healthy
      bookingdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  notifications:
    image: "keskink/notificationservice:v1"
    container_name: notificationms
    platform: linux/amd64
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "notificationservice"
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://notificationdb:5432/notificationdb"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      rabbit:
        condition: service_healthy
      notificationdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  gatewayserver:
    image: "keskink/gatewayserver:v1"
    container_name: gatewayserverms
    platform: linux/amd64
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      bookings:
        condition: service_healthy
      notifications:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SERVER_PORT: 8070
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8888/
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  message:
    image: "keskink/message:v1"
    container_name: messagems
    platform: linux/amd64
    depends_on:
      rabbit:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    extends:
      file: common-config.yml
      service: network-deploy-service


networks:
  bookingapp:
    driver: "bridge"



